import{CONFIG}from"./config.js";
import{current}from"./filters.js";
import{html,attr,fmtDate,hasRealLink,weatherText}from"./utils.js";
let openDialog=null;
export function setDialogHandler(fn){openDialog=fn}
export function summary(el,items){const c={emergency:0,warning:0,watch:0,advisory:0};items.forEach(a=>c[a.severity]=(c[a.severity]||0)+1);el.innerHTML=`<div><strong>${c.emergency}</strong><small>Emergency</small></div><div><strong>${c.warning}</strong><small>Warning</small></div><div><strong>${c.watch}</strong><small>Watch</small></div><div><strong>${c.advisory}</strong><small>Advisory</small></div>`}
export function feed(el,items,mode,query=""){const f=current(mode);const q=query.trim().toLowerCase();let arr=items.filter(a=>(f==="all"||a.category===f||a.severity===f||a.sourceClass===f||a.type?.toLowerCase().includes(f)) && (!q||(a.title+" "+a.summary+" "+(a.areas||[]).join(" ")+" "+a.source).toLowerCase().includes(q)));if(!arr.length){el.innerHTML=`<p style="text-align:center;padding:30px;font-size:13px;color:#666">No ${mode==="incidents"?"incidents/news":"critical alerts"} found.</p>`;return}el.innerHTML=arr.slice(0,CONFIG.maxItems).map(card).join("");el.querySelectorAll("[data-dialog-id]").forEach(node=>{node.onclick=e=>{e.preventDefault();const item=arr.find(x=>x.id===node.dataset.dialogId);if(item&&openDialog)openDialog(item)}})}
function badge(s){return{emergency:"🔴 Emergency",warning:"🟠 Warning",watch:"🟡 Watch",advisory:"🟢 Advisory"}[s]||"🟢 Advisory"}
function card(a){const sev=a.severity||"advisory";const areas=(a.areas||[]).slice(0,5).join(", ")||"Selected region";const srcCount=a.sources?.length||1;const attrs=hasRealLink(a.link)?`href="${attr(a.link)}" target="_blank" rel="noopener noreferrer"`:`href="#" data-dialog-id="${attr(a.id)}"`;return`<a class="card ${sev}" ${attrs}><span class="badge ${sev}">${badge(sev)}</span><span class="sourceTag">${a.sourceClass==="official"?"OFFICIAL":srcCount>1?srcCount+" SOURCES":"LIVE NEWS"}</span><span class="confidence">Confidence ${a.confidence||"Medium"}</span><h3>${a.icon||"ℹ️"} ${html(a.type||a.category||"Update")} — ${html(a.title)}</h3><div class="meta"><span style="color:#b71c1c">📍 ${html(areas)} | ${html(a.source||"Source")}</span><span>⏰ ${fmtDate(a.lastUpdated||a.pubDate)}</span></div><div class="alert-extra"><strong>Action:</strong> ${html(a.action||"Check official source before acting.")}<br><strong>Summary:</strong> ${html(a.summary||"Open source for more details.")}</div></a>`}
export function weather(el,w){if(!w){el.innerHTML=`<div class="weather-card"><strong>--</strong><small>Weather unavailable</small></div>`;return}el.innerHTML=`<div class="weather-card"><strong>${Math.round(w.temp)}°C</strong><small>Temperature</small></div><div class="weather-card"><strong>${weatherText(w.code)}</strong><small>Condition</small></div><div class="weather-card"><strong>${w.rainChance??"--"}%</strong><small>Rain Chance</small></div><div class="weather-card"><strong>${w.rain??0} mm</strong><small>Rain Now</small></div><div class="weather-card"><strong>${Math.round(w.wind??0)} km/h</strong><small>Wind</small></div><div class="weather-card"><strong>${w.humidity??"--"}%</strong><small>Humidity</small></div><div class="weather-card"><strong>${w.visibility??"--"} km</strong><small>Visibility</small></div><div class="weather-card"><strong>${Math.round(w.gust??0)} km/h</strong><small>Gust</small></div>`}
